### ISSUE TITLE
Raml::UnsupportedRamlVersion for RAML 1.0

### ISSUE THREAD

**Issue by jankeesvw** [rzane/rspec-raml#2]
I work on a project that uses RAML 1.0, when I try to use this library I get `Raml::UnsupportedRamlVersion: Raml::UnsupportedRamlVersion`

**Comment by rzane** [comment]
Yeah, unfortunately, I bet on this gem: https://github.com/coub/raml_ruby, which doesn't support 1.0.

Looks like this one supports it: https://github.com/jpb/raml-rb. Any you interest in making a PR?

**Comment by jankeesvw** [comment]
I don't think I have the time to work on this unfortunately, thanks for the links to the gems!

**Comment by mwmeyer** [comment]
@rzane Any development on this? I see that master had a commit that looks like it might have added support for 1.0 but then it was reverted? https://github.com/rzane/rspec-raml/commit/d8c0fbff34433530523aad4a9c624a2c5f4606ac
